version: "3.8"

services:
  bot:
    build: .
    x-develop:
      watch:
        - action: sync
          path: .
          target: /app

#  db:
#    image: mysql
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'wallet'
#      MYSQL_ROOT_PASSWORD: pwd
#    ports:
#      - '3306:3306'
#    expose:
#      - '3306'
#
#volumes:
#  my-db:

#  db:
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: pwd
#
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
