version: "3.8"

volumes:
  mysql_data: { }

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
        - mysql_data:/var/lib/mysql
    env_file:
      - .env
#  bot:
#    build: .
#    x-develop:
#      watch:
#        - action: sync
#          path: .
#          target: /app
